
"""add_proficiency_field

Revision ID: 16cda22d41e7
Revises: 2ad348dce409
Create Date: 2026-01-14 00:28:10.224086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16cda22d41e7'
down_revision: Union[str, None] = '2ad348dce409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('proficiency', sa.Float(), nullable=False, server_default='1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'proficiency')
    # ### end Alembic commands ###
