
"""add_session_fields

Revision ID: 2ad348dce409
Revises: 5b777ebdeb55
Create Date: 2026-01-14 00:06:33.556213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ad348dce409'
down_revision: Union[str, None] = '5b777ebdeb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('current_level', sa.Integer(), nullable=False, server_default="1"))
    op.add_column('learning_sessions', sa.Column('total_correct', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('learning_sessions', sa.Column('total_questions', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'total_questions')
    op.drop_column('learning_sessions', 'total_correct')
    op.drop_column('learning_sessions', 'current_level')
    # ### end Alembic commands ###
